<div class="page-header">
    <h1>Diversity</h1>
</div>
<div id="block-mine">
    <p style="text-align: justify;">
        The SunshinePHP Developer Conference is dedicated to providing a harassment-free conference experience for everyone, regardless of gender, sexual orientation, disability, physical appearance, body size, race, or religion.  We will not tolerate harassment of conference participants in any form.  Sexual language and imagery is not appropriate for any conference venue, including talks.  Conference participants violating these rules may be sanctioned or expelled from the conference without a refund at the discretion of the conference organizers.
        
        Enjoy the conference responsibly.  Thank you.
    </p>
</div>