<div class="page-header">
    <h1>About</h1>
</div>
<div id="block-mine">
    <p style="text-align: justify;">
        The South Florida PHP Users Group (SoFloPHP) is a users group for PHP developers and dedicated to growing the PHP Community in the South Florida area.  With monthly user group meetings and other events, the user group is going strong with 500+ members from Jupiter down to Miami.<br /><br />

        The user group has hosted many speakers from other areas in an effort to bring the best to its members.  With guest speakers like Rasmus Lerdorf, Derrick Rethans, and Lukas K. Smith, as well as local speakers we continue to grow and learn.<br /><br />

        Adam Culp , the organizer of the SoFloPHP, is the main point of contact for this event and is ready to take any questions and/or offers for help.  He has been a driving force behind the user group for the past 2 (almost 3) years.  Adam is a frequent speaker at local events, and continues to build the PHP community in South Florida.  Often sought out for his opinions and expertise, he has helped many local businesses organize current development teams or build new teams for upcoming projects.<br /><br />

        Pablo Godel started using PHP in 1995 and became involved in the PHP community early on as he created the first mailing list for Spanish speaking developers, and handed it to the PHP group with over 1,000 members.  He regularly contributes code, documentation, and other means to various projects like Symfony, Doctrine, Composer and many more.  He has spoken at numerous PHP conferences and events in the U.S. and across Europe.  Even when not speaking he enjoys assisting with as many conferences as he can, and is now lending a hand to the SunshinePHP Developer Conference.<br /><br />
        
        <h3>About the conference</h3>

        The SunshinePHP Developer Conference is a conference by developers for developers, and is dedicated to helping grow the PHP community in South Florida and the world.  Held in Miami, Florida at the Embassy Suite Miami International just a very short drive from the Miami International Airport.<br /><br />

        During this 2-day 3 track conference of 30 talks/sessions we will dedicate one track to PHP framework talks, making this the first Symfony event on the east coast. (NOTE: Anyone attending the conference will be able to attend any talks they choose.)<br /><br />
        
        <h3>Quick Info</h3>

        <a href="/contact" title="Contact Us">Contact us</a> if you have any questions regarding the conference, tutorials, the venue, travel and/or the hotel.
    </p>
</div>