<div class="page-header">
    <h1>Conduct</h1>
</div>
<div id="block-mine">
    <p style="text-align: justify;">
        The SunshinePHP Developer Conference is dedicated to providing a harassment-free 
        conference experience for everyone, regardless of gender, sexual orientation, 
        disability, physical appearance, race, or religion. Harassment of any conference
        participants in any form will not be tolerated.  This extends to
        sexual language and/or imagery which is not appropriate for any conference venue,
        including talks. Conference participants violating these rules may be sanctioned
        or expelled from the conference without a refund at the discretion of conference
        organizers.<br /><br />
        
        If you experience any problems of this nature at the event please contact 
        one of the event organizers, and/or report it to the registration desk.<br /><br />
        
        Enjoy the conference responsibly.  Thank you.
    </p>
</div>