<div class="page-header">
    <h1>Code of Conduct</h1>
</div>
<div id="block-mine">
    <ol>
        <li><h3>Purpose</h3>
            <p>SunshinePHP Developer Conference is a community event and is open to all. We are committed to a safe, professional environment for everyone and will not tolerate harassment or offensive behavior of any kind.</p>
        </li>
        <li><h3>Our Commitment to You</h3>
            We are enthusiastically focused on improving our event and making it a place that is welcoming to all. All reports will be taken seriously, handled respectfully, and dealt with in a timely manner.
        </li>
        <li><h3>Examples of Behavior</h3>
            <strong>Examples of offensive behavior include, but are not limited to:</strong><ul>
                <li>Making sexually explicit or suggestive comments</li>
                <li>Making fun of or denigrating someone based on their race, gender, physical appearance, preferred framework/platform, etc.</li>
                <li>Continuing to talk to someone after they have indicated for it to stop</li>
                <li>Suggestive, sexual, or physical contact without someone's explicit consent</li>
            </ul>
            If someone is unsure if a behavior is acceptable, they should ask themselves "Does this build up and encourage someone? Is this appropriate in a professional setting?" If there is still doubt, <a href="/contact">please contact the organizers</a>.</p>
        </li>
        <li><h3>What to Do When an Incident Occurs</h3>
            <ul>
                <li>If asked to stop a violating behavior, an individual is expected to comply immediately, even if they do not believe the behavior violates this Code of Conduct. If there are concerns about being asked to stop this behavior, <a href="/contact">please contact the organizers</a> as soon as possible.</li>
                
                <li>If you have an incident to report, please talk to any <a href="/contact">organizer</a> or to the registration desk immediately while at the event or <a href="/contact">email the organizers</a>. Reports can be made anonymously via the email form, but we encourage you to include contact information so we can more fully assist and follow-up if needed. </li>
            </ul>
        </li>
        <li><h3>Consequences</h3>
            Any participant at any of our activities that is violating the Code of Conduct will be dealt with at the discretion of the organizers and may be removed without opportunity for refund.
        </li>
        <li><h3>Procedure for Handling an Incident Report</h3>
            <ol>
                <li>Ask if the victim feels safe and if there is anything we can do immediately to improve the situation</li>
                <li>When a report is made verbally, listen attentively while taking written notes on the details of the incident. Confirm with the reporter when finished that the notes contain all pertinent information. Be sure to include details such as:<ul>
                        <li>Date and time of the incident</li>
                        <li>Names/descriptions of those involved in the incident and any witnesses</li>
                        <li>Description of what transpired and why it violates the Code of Conduct</li>
                        <li>Contact information of the reporter to follow up if needed</li>
                        <li>What the reporter/victim would like to see happen and anything they need to help them feel safe</li>
                    </ul></li>
                <li>Contact the other organizers immediately to discuss the situation</li>
                <li>As a group, the organizers will confer and decide on an appropriate course of action, which may include (but is not limited to):<ul>
                        <li>Initiating mediation between the conflicting parties to help them work it out</li>
                        <li>Discussing the issue with the offending party and insuring that the behavior will not continue</li>
                        <li>Removing the offending party from the event without opportunity for refund</li>
                        <li>Contacting local authorities in extreme circumstances if needed</li>
                    </ul></li>
                <li>Enact the agreed upon resolution</li>
                <li>Follow up with the parties involved as needed</li>
            </ol>
        </li>
</div>