<div class="page-header">
    <h1>Events</h1>
</div>
<div id="block-mine">
    <p style="text-align: justify;">
        
        There's more to SunshinePHP than a day full of tutorials followed by two days of talks.  We have arranged many great evening activities to push your conference experience over the top!<br /><br />
    
        Among the extra activities are ways to improve your coding skills, hear other experienced developers speak about "niche" topics, or just provide a great opportunity to socialize with other great PHP developers and project leaders from around the globe.<br /><br />
    
        <h3>Happy Hour</h3>
    
        Happy Hour all 3 nights at SunshinePHP is about more than a bunch of geeks hanging out and getting drunk.  While there are beverages available to meet any taste, this is an open atmosphere where games, music, and socializing are the best part of the menu.<br /><br />
    
        <h3>Hack-a-thon</h3>
    
        On the evening of February 6th <a href="http://in2it.be" title="in2it">in2it</a> will be hosting of our 3rd annual hack-a-thon.  Last year was a blast, and some teams created pretty awesome apps.  This is a great opportunity to pair program, or just watch and learn, with some of the best PHP developers around.  Like you!  More details coming soon.<br /><br />
    
        <h3>Uncon</h3>
    
        This year our <a href="/uncon" title="Uncon">Uncon</a> will be a complete 4th track added to the normal 3 track conference.  So if you have a talk you've been dying to give, or have been trying to break into the conference speaking circuit, this is a great chance for you to do it.  Bring your talk and see us during the conference to get your slot.  <a href="/uncon" title="Uncon">Click Here for more details.</a><br /><br />

        <h3>Hallway Track</h3>
    
        Everyone knows the "Hallway Track" is the best part of a good conference, and SunshinePHP doesn't disappoint.  With so many BIG names coming to speak you can be sure there will be many more well known PHP developers from around the globe.  The space between talks, and sometimes even during talks, is a great time to catch someone you've always wanted to meet and ask some questions.<br /><br />

        <h3>Speakers Dinner</h3>
    
        Sorry, but this event is for speakers only.  February 5th at 7:00pm we will be providing a shuttle for the speakers to an awesome secret dinner as a thank you for their contribution to the conference.<br /><br />
        
    </p>
</div>