<div class="page-header">
    <h1>Conduct</h1>
</div>
<div id="block-mine">
    <div class="row">
        <div class="col-md-12">
            <h3>Environment</h3>
            
            <p>SunshinePHP Developer Conference maintains a welcoming, friendly, polite, and professional environment. Developers of all skill levels are welcome. We have a Code of Conduct that all attendees must agree to when purchasing their ticket. We take all Code of Conduct reports seriously, and our Code of Conduct will be enforced. For more information, please see <a href="/conduct">the SunshinePHP Developer Conference Code of Conduct</a>.</p>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-6 col-md-push-6">
            <img src="/assets/images/check-in.jpg" class="img-responsive img-thumbnail" alt="Madison PHP check-in desk">
        </div>
        <div class="col-md-6 col-md-pull-6">
            <h3>Arriving</h3>
            <p>Directions to the conference are located on our <a href="/venue/">Venue page</a>. When you arrive at <a href="/venue/">the Radisson Hotel Madison</a>, park in one of the lots surrounding the hotel (please do not park in front of any of the stores in the nearby strip mall. Parking is complimentary.</p>
            
            <p>Enter the front doors under the awning at the front of the hotel, proceed through the lobby, and turn left. You will see a registration table with the red Madison PHP logo on the front of it. Check in at this table.</p>
            
            <h3>Getting Help</h3>
            
            <p>If you need assistance at any time, any one of <a href="/organizers/">our organizers</a> would be happy to help you out. The organizers will be moving around the venue, but the easiest place to find them will be at the registration table (with the red Madison PHP logo on the front of it).</p>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-6 col-md-push-6">
            <img src="/assets/images/talk-tables.jpg" class="img-responsive img-thumbnail" alt="audience in a talk sitting at tables">
            <img src="/assets/images/talk-speaker.jpg" class="img-responsive img-thumbnail" alt="speaker by the slides speaking to an audience">
        </div>
        <div class="col-md-6 col-md-pull-6">
            <h3>Talks</h3>
            
            <p>The rooms for the talks will be to the right and left of the registration area. Each talk room will be clearly labeled on the schedule. If you have any questions about which room a certain talk is in, stop by the registration table.</p>
            
            <p>Our goal is to have the chairs set at tables to make it easy to take notes and/or follow along on a laptop. This may not always be possible, but we will be working to ensure as many chairs have table space as possible.</p>
            
            <p>The talks will be accompanied by slides projected on large screens at the front of the room. The largest room will have two screens. The speakers will have microphones.</p>
            
            <p>If you need any table or seating accomodations, visual aid, or audio assistance, please <a href="http://sunshinephp.com/contact">send us an email to let us know what you need</a>. We will do our best to assist you.</p>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-6 col-md-push-6">
            <img src="/assets/images/lunch.jpg" class="img-responsive img-thumbnail" alt="audience eating lunch together">
        </div>
        <div class="col-md-6 col-md-pull-6">
            <h3>Food</h3>
            
            <p>Lunch will be provided on-site. If you have any dietary restrictions, please let us know when you purchase your ticket or if you have already purchased your ticket, please <a href="http://sunshinephp.com/contact">send us an email to let us know about your dietary restrictions</a>. Our caterer is happy to work with you on this. We must receive your dietary restrictions at least two weeks prior to the event for our catering requirements. If it is closer than two weeks to the event, we will do our best to accommodate you, but we may not be able to.</p>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-6 col-md-push-6">
            <img src="/assets/images/open-space.jpg" class="img-responsive img-thumbnail" alt="Vendor area and Beverages">
        </div>
        <div class="col-md-6 col-md-pull-6">
            <h3>Vendor Area and Hallway Track</h3>
            
            <p>The main open space and lounge area will contain vendor tables and space to hang out and network with fellow attendees.</p>
        
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-6 col-md-push-6">
            <img src="/assets/images/coffee.jpg" class="img-responsive img-thumbnail" alt="coffee, tea, and soda service">
        </div>
        <div class="col-md-6 col-md-pull-6">
            <h3>Beverages</h3>
            
            <p>Water will be available at the venue. Additionally, if we get sponsors for them, we may also have coffee, tea, and/or soda available. These would be located in the vendor/lounge area.</p>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-6 col-md-push-6">
            <img src="/assets/images/book-swap.jpg" class="img-responsive img-thumbnail" alt="Madison PHP Book Swap">
        </div>
        <div class="col-md-6 col-md-pull-6">
            <h3>Free Stuff</h3>
            
            <p>We will have a table labeled "Free Swag Table" where vendors have donated stickers, tshirts, and other items. You may take any of the items on this table (except the sign) free of charge. We ask that you please be considerate of others and only take one of each item per person until after lunch. After lunch, you may take as much as you'd like.</p>
            
            <h3>Free Books</h3>
            <p>We will have a table labeled "Free Books" where you can find books donated by vendors and other attendees. If you have any old tech-related books that you no longer want, feel free to place them on this table. Looking for a new tech book to read? Stop by and take whatever you'd like.</p>
        </div>
    </div>
</div>