<div class="featurette">
    <div class="container">
        <div class="row">
            <div id="col1" class="span3">
                <div class="cycle-slideshow">
                    <img src="/img/ssphp-slider/13.jpg" class="slide" />
                    <img src="/img/ssphp-slider/20.jpg" class="slide" />
                    <img src="/img/ssphp-slider/18.jpg" class="slide" />
                    <img src="/img/ssphp-slider/15.jpg" class="slide" />
                </div>
            </div>
            <div id="col2" class="span3">
                <div class="cycle-slideshow">
                    <img src="/img/ssphp-slider/5.jpg" class="slide" />
                    <img src="/img/ssphp-slider/10.jpg" class="slide" />
                    <img src="/img/ssphp-slider/1.jpg" class="slide" />
                    <img src="/img/ssphp-slider/8.jpg" class="slide" />
                </div>
            </div>
            <div id="col3" class="span3">
                <div class="cycle-slideshow">
                    <img src="/img/ssphp-slider/9.jpg" class="slide" />
                    <img src="/img/ssphp-slider/6.jpg" class="slide" />
                    <img src="/img/ssphp-slider/11.jpg" class="slide" />
                    <img src="/img/ssphp-slider/17.jpg" class="slide" />
                </div>
            </div>
            <div id="col4" class="span3">
                <div class="cycle-slideshow">
                    <img src="/img/ssphp-slider/21.jpg" class="slide" />
                    <img src="/img/ssphp-slider/12.jpg" class="slide" />
                    <img src="/img/ssphp-slider/14.jpg" class="slide" />
                    <img src="/img/ssphp-slider/16.jpg" class="slide" />
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="span12">
            <div class="row">
                <div class="span9">
                    <section id="block-download">
                        <?php /*echo $this->navigation('navigation')
                            ->breadcrumbs()
                            ->setMinDepth(0)
                            ->setPartial(array('partial/breadcrumb.phtml', 'Application'));*/
                        ?>
                        <div class="page-header">
                            <h1>SunshinePHP Conference!</h1>
                        </div>
                        <div id="block-mine">
                            <p style="text-align: justify">
                                The SunshinePHP Developer Conference is hosted by the South Florida PHP community (<a href="http://soflophp.org" title="SoFloPHP">SoFloPHP</a>) 
                                in Miami, Florida from February 2nd - 4th, 2017, and <strong>you're invited!</strong>
                                We'll host some of the best speakers,
                                awesome talk topics, latest technologies, and up to date news in PHP. And don't 
                                forget our Hack-a-thon and Uncon'ference, as well as a great hallway track!<br /><br />
                                
                                The conference has something for every level of PHP developer. We start on February 2nd with a full
                                day of 8 PHP related tutorials and workshops
                                that are each 3 hours of in-depth information. Next we follow that with 2 days on February 3rd and 4th containing 5 keynotes and
                                40 PHP talks over 4 tracks.<br /><br />
                                
                                So come warm up for awhile in February and meet other PHP developers to see what others are doing, and share your experience
                                as well. Then relax or have some fun at the evening events with plenty of fun for everyone!
                            </p>
                            <p>&nbsp;</p>
                        </div>
                        <div class="row">
                            <div class="span3">
                                <div class="breakout">By Developers For Developers</div>
                                <div style="text-align: justify">
                                    This conference is being led by active PHP community members who focused on
                                    keeping costs low while still holding one of the best conferences in PHP, 
                                    making it easier for developers to attend. We also kept the dates closer 
                                    to the weekend so getting time off is less of an issue.
                                </div>
                            </div>
                            <div class="span3">
                                <div class="breakout">Great Speakers</div>
                                <div style="text-align: justify">
                                    The amount of talk proposals from speakers around the globe were overwhelming! 
                                    Sadly we were only able to select 40 of them. However, we feel confident the talks chosen
                                    offer something for everyone. So please come join us, as we share and learn.
                                </div>
                            </div>
                            <div class="span3">
                                <div class="breakout">Awesome Sponsors</div>
                                <div style="text-align: justify">
                                    SunshinePHP is made possible through many wonderful sponsor contributions. We 
                                    are very thankful to each and every sponsor who steps up and invests in making 
                                    this conference possible. Please join us by supporting these wonderful companies.
                                </div>
                            </div>
                        </div>
                        <p>&nbsp;</p>
                        <div class="row">
                            <div class="span3">
                                <div class="breakout">Twitter</div>
                                <a class="twitter-timeline"  href="https://twitter.com/SunShinePHP" data-widget-id="261104655206072320">Tweets by @SunShinePHP</a>
                                <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
                            </div>
    
                            <div class="span3">
                                <div class="breakout">Facebook</div>
                                <div id="fb-root"></div>
                                <script>(function(d, s, id) {
                                        var js, fjs = d.getElementsByTagName(s)[0];
                                        if (d.getElementById(id)) return;
                                        js = d.createElement(s); js.id = id;
                                        js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=215932875123186";
                                        fjs.parentNode.insertBefore(js, fjs);
                                    }(document, 'script', 'facebook-jssdk'));</script>
                                <div class="fb-like-box" data-href="http://www.facebook.com/sunshineconf" data-width="250" data-show-faces="true" data-stream="false" data-header="true"></div>
                            </div>

                            <div class="span3">
                                <div class="breakout">Important Info!</div>
                                <ul><strong>Info</strong>
                                    <li>Hashtag: #sunphp17</li>
                                    <li>Twitter: <a href="http://twitter.com/sunshinephp" title="@SunshinePHP on Twitter" target="_blank">@sunshinephp</a></li>
                                    <li>Facebook: <a href="http://facebook.com/sunshineconf" title="SunshinePHP on Facebook" target="_blank">SunshineConf</a></li>
                                </ul>
                                <ul><strong>Dates</strong>
                                    <li>Start CFP - Aug 15th, 2016</li>
                                    <li>End CFP - Sep 30th, 2016</li>
                                    <li>Talks Announced - Oct 15th, 2016</li>
                                    <li>Sched. Final - Oct 30th, 2016</li>
                                    <li>Tutorial Day - Feb 2nd, 2017</li>
                                    <li>Conferenece - Feb 3rd-4th, 2017</li>
                                </ul>
                            </div>
                        </div>
                        
                    </section>
                </div>
                
                <?php echo $this->sidebar(); ?>
                
            </div>
        </div>
    </div>
</div>