<div class="container">
    <div class="row">
        <div class="span12">
            <div class="row">
                <div class="span9">
                    <section id="block-download">
                        <ul class="breadcrumb">
                            <li><a href="/">Home</a> <span class="divider">/</span></li>
                            <li class="active">SunshinePHP Conference</li>
                        </ul>
                        <div class="page-header">
                            <h1>Registration</h1>
                        </div>
                        <div id="block-mine">
                            <p>Using the form below please register for the 2014 SunshinePHP Developer Conference!</p>
                            <p>&nbsp;</p>

                            <div style="width:100%; text-align:left;" >
                                <iframe  src="http://www.eventbrite.com/tickets-external?eid=7836843209&ref=etckt&v=2" frameborder="0" height="400" width="100%" vspace="0" hspace="0" marginheight="5" marginwidth="5" scrolling="auto" allowtransparency="true"></iframe>
                                <div style="font-family:Helvetica, Arial; font-size:10px; padding:5px 0 5px; margin:2px; width:100%; text-align:left;" >
                                    <a style="color:#ddd; text-decoration:none;" target="_blank" href="http://www.eventbrite.com/r/etckt">Sell Tickets</a> <span style="color:#ddd;">through</span> <a style="color:#ddd; text-decoration:none;" target="_blank" href="http://www.eventbrite.com?ref=etckt">Eventbrite</a>
                                </div>
                            </div>

                        </div>

                    </section>
                </div>
                <?php echo $this->sidebar(); ?>
            </div>
        </div>
    </div>
</div>