<div class="page-header">
    <h1>Pricing & Registration</h1>
</div>
<div id="block-mine">
    <p>Using the form below please register for the SunshinePHP Developer Conference!</p>
    <p>
        <strong>NOTE:</strong> If you are using a mobile device the form below may not work as expected.<br />
        Instead use <a href="https://sunshinephp2015.eventbrite.com/" title="SunshinePHP on Eventbrite" target="_blank">this link</a>.
    </p>

    <div style="width:100%; text-align:left;" >
        <iframe  src="http://eventbrite.com/tickets-external?eid=12448841821&ref=etckt" frameborder="0" height="400" width="100%" vspace="0" hspace="0" marginheight="5" marginwidth="5" scrolling="auto" allowtransparency="true"></iframe>
        <div style="font-family:Helvetica, Arial; font-size:10px; padding:5px 0 5px; margin:2px; width:100%; text-align:left;" ><a style="color:#ddd; text-decoration:none;" target="_blank" href="http://www.eventbrite.com/r/etckt">Online event registration</a>
            <span style="color:#ddd;"> for </span><a style="color:#ddd; text-decoration:none;" target="_blank" href="https://www.eventbrite.com/e/sunshinephp-conference-2015-registration-12448841821?ref=etckt">SunshinePHP Conference 2015</a> <span style="color:#ddd;">powered by</span> <a style="color:#ddd; text-decoration:none;" target="_blank" href="http://www.eventbrite.com?ref=etckt">Eventbrite</a>
        </div>
    </div>

    <h3>Cancellation Policy:</h3>

    <p>Cancellations of conference registrations made prior to December 15th, 2014 are subject to a cancellation fee. Cancellations made thereafter are <strong>nonrefundable</strong>. All cancellations must be made via our <a href="/contact" title="Contact Form">Contact Form</a>. Substitutions may be made at any time, also by using our <a href="/contact" title="Contact Form">Contact Form</a>. Confirmed registrants who do not attend the conference will not receive a refund and are liable for the entire fee. Cancellations of travel and hotel arrangements are the responsibility of the registrant. SunshinePHP reserves the right to refuse registrations. Due to insurance restrictions, no one under 18 will be admitted to the conference. All speakers, programs and descriptions are subject to change without notice.</p>
    
    <p>The only exception to this policy is in the case of an international attendee not being granted a U.S. Visa to enter the country, because they must purchase a ticket in order to receive an introduction letter for the Visa application.</p>
</div>