<div class="page-header">
    <h1>Pricing & Registration</h1>
</div>
<div id="block-mine">
    <p>Using the form below please register for the SunshinePHP Developer Conference!</p>
    <p>
        <strong>NOTE:</strong> If you are using a mobile device the form below may not work as expected.
        Instead please use <a href="https://sunshinephp2017.eventbrite.com/" title="SunshinePHP on Eventbrite" target="_blank">this link</a>.
    </p>
    
    <!-- <h3>Sorry, we're SOLD OUT!</h3>
    
    <p>Sorry, but yes, we are sold out! However, <strong>you can still add yourself to the waitlist</strong> and if something opens up we will contact folks on a first-come/first-served basis. Unfortunately this does not apply to the tutorial day.</p> -->

    <div style="width:100%; text-align:left;" ><iframe  src="//eventbrite.com/tickets-external?eid=27146010448&ref=etckt" frameborder="0" height="610" width="100%" vspace="0" hspace="0" marginheight="5" marginwidth="5" scrolling="auto" allowtransparency="true"></iframe><div style="font-family:Helvetica, Arial; font-size:10px; padding:5px 0 5px; margin:2px; width:100%; text-align:left;" ><a class="powered-by-eb" style="color: #dddddd; text-decoration: none;" target="_blank" href="http://www.eventbrite.com/r/etckt">Powered by Eventbrite</a></div></div>
    
    <p>By registering for the conference you agree to abide by the <a href="/conduct" title="Code of Conduct">Code of Conduct</a>.</p>

    <h3>Cancellation Policy:</h3>

    <p>Cancellations of conference registrations made prior to December 15th are subject to a cancellation fee. Cancellations made thereafter are <strong>nonrefundable</strong>. All cancellations must be made via our <a href="/contact" title="Contact Form">Contact Form</a>. Substitutions may be made at any time, also by using our <a href="/contact" title="Contact Form">Contact Form</a>. Confirmed registrants who do not attend the conference will not receive a refund and are liable for the entire fee. Cancellations of travel and hotel arrangements are the responsibility of the registrant. SunshinePHP reserves the right to refuse registrations. Due to insurance restrictions, no one under 18 will be admitted to the conference. All speakers, programs and descriptions are subject to change without notice.</p>
    
    <h3>VAT Invoices</h3>
    
    <p>This conference is organized by a U.S. based entity and is held in the U.S. Thus there is no need of a VAT invoice for registrations of EU based attendees. After registration a confirmation email with all related financial information is automatically sent to the registrant. Nothing more is available.</p>

    <h3>International Attendees:</h3>

    <p>The only exception to our cancellation policy is in the case of an international attendee not being granted a U.S. Visa to enter the country, because they must purchase a ticket in order to receive an invitation letter to include in the U.S. Visa application.</p>

    <p>For those attendees who are required to gain a U.S. Visa there are some steps that need to be followed:<br>
        <ul>
            <li>First, purchase a ticket to the conference.</li>
            <li>Then, send us the vital information below so we can generate an invitation letter for you.</li>
        <li>Wait for the invitation letter, typically 1 to 2 days. (<a href="files/sample_invitation_letter.pdf" title="SunshinePHP sample invitation letter">Here is a sample</a>)</li>
            <li>If your U.S. Visa application is rejected, simply email us a copy of the rejection letter for <strong>immediate full refund</strong> which will go back on the card used for purchase.</li>
        </ul><br>
        The information we need to prepare the invitation letter is:<br><br>
    
        <strong>Name:</strong> {name}<br>
        <strong>Job Title:</strong> {title}<br>
        <strong>Company:</strong> {company}<br>
        <strong>Address 1:</strong> {address1}<br>
        <strong>Address 2:</strong> {address2}<br>
        <strong>City/Postal Code:</strong> {city} {postal_code}<br>
        <strong>Country:</strong> {country}<br>
        <strong>Phone:</strong> {phone}<br>
        <strong>E-mail:</strong> {email}<br>
        <strong>Passport No.:</strong> {passport_number}<br>
        <strong>Passport Expiration Date:</strong> {passport_expiration_date}<br>
        <strong>Date of Birth:</strong> {date_of_birth}<br><br>
    
        Email the above information to: Contact[at]SunshinePHP[dot]com or use our <a href="/contact" title="Contact Form">Contact Form</a>.
    </p>
</div>