<div class="page-header">
    <h1>Schedule</h1>
</div>
<div id="block-mine">
    <div id="schedule">
        <table>
            <tbody>
            <tr>
                <th colspan="4">Wednesday Feb. 5th, 2014</th>
            </tr>
            <tr>
                <td class="time_column">17:30 &#8211; 19:30</td>
                <td class="keyrow" colspan="3"><strong>Happy Hour by php|architect</strong> for those who are early</td>
            </tr>
            </tbody>
        </table>
        <hr />
        <table>
            <tbody>
            <tr>
                <th colspan="4">Thursday Feb. 6th, 2014</th>
            </tr>
            <tr>
                <td class="time_column">17:30 &#8211; 19:30</td>
                <td class="keyrow" colspan="3"><strong>Happy Hour by php|architect</strong> for those who are early</td>
            </tr>
            </tbody>
        </table>
        <hr />
        <table>
            <tbody>
            <tr>
                <th colspan="4">Day 1 &#8211; Friday Feb. 7th, 2014</th>
            </tr>
            <tr>
                <td>Room</td>
                <td>Key Largo 1 (front)</td>
                <td>Grand Ballrooom</td>
                <td>Key Largo 2 (rear)</td>
            </tr>
            <tr>
                <td class="time_column">8:00 &#8211; 9:00</td>
                <td class="keyrow" colspan="3">Registration Opens</td>
            </tr>
            <tr>
                <td>9:00 &#8211; 10:00</td>
                <td class="keyrow" colspan="3">Opening Keynote<br />
                    PHP in 2013<br />
                    <a title="Speaker Rasmus Lerdorf" href="http://2013.sunshinephp.com/schedule/speakers/#rasmus-lerdorf">Rasmus Lerdorf</a></td>
            </tr>
            <tr>
                <td>10:15 &#8211; 11:15</td>
                <td class="talk1_column"><a title="Talk: Symfony2 Introduction" href="http://2013.sunshinephp.com/schedule/talks/#symfony2-introduction"><strong>Symfony2 Intro</strong></a><br />
                    - <a title="Speaker David Buchmann" href="http://2013.sunshinephp.com/schedule/speakers/#david-buchmann">David Buchmann</a> -</td>
                <td class="talk2_column"><a title="Talk: Continuous Integration in Real Life" href="http://2013.sunshinephp.com/schedule/talks/#continuous-integration-in-real-life"><strong>Continuous Integration in Real Life</strong></a><br />
                    - <a title="Speaker Beth Tucker Long" href="http://2013.sunshinephp.com/schedule/speakers/#beth-tucker-long">Beth Tucker Long</a> -</td>
                <td class="talk3_column"><a title="Talk: Functional PHP" href="http://2013.sunshinephp.com/schedule/talks/#functional-php"><strong>Functional PHP</strong></a><br />
                    - <a title="Speaker Larry Garfield" href="http://2013.sunshinephp.com/schedule/speakers/#larry-garfield">Larry Garfield</a> -</td>
            </tr>
            <tr>
                <td>11:30 &#8211; 12:30</td>
                <td><a title="Talk: Introduction to Modules in Zend Framework 2" href="http://2013.sunshinephp.com/schedule/talks/#introduction-to-modules-in-zend-framework2"><strong>Introduction to Modules in Zend Framework 2</strong></a><br />
                    - <a title="Speaker Evan Coury" href="http://2013.sunshinephp.com/schedule/speakers/#evan-coury">Evan Coury</a> -</td>
                <td><a title="Talk: It Was Like That When I Got Here Steps Toward Modernizing a Legacy Codebase" href="http://2013.sunshinephp.com/schedule/talks/#it-was-like-that-when-i-got-here-steps-toward-modernizing-a-legacy-codebase"><strong>It Was Like That When I Got Here: Steps Toward Modernizing a Legacy Codebase</strong></a><br />
                    - <a title="Speaker Paul M. Jones" href="http://2013.sunshinephp.com/schedule/speakers/#paul-m-jones">Paul M. Jones</a> -</td>
                <td><a title="Talk: Twig Tips and Tricks" href="http://2013.sunshinephp.com/schedule/talks/#twig-tips-and-tricks"><strong>Twig Tips and Tricks</strong></a><br />
                    - <a title="Speaker Javier Equiluz" href="http://2013.sunshinephp.com/schedule/speakers/#javier-equiluz">Javier Equiluz</a> -</td>
            </tr>
            <tr>
                <td>12:30 &#8211; 13:30</td>
                <td class="keyrow" colspan="3">Lunch</td>
            </tr>
            <tr>
                <td>13:30 &#8211; 14:30</td>
                <td>
                    <a title="Talk: Introducing Tests in Legacy PHP Applications" href="http://2013.sunshinephp.com/schedule/talks/#introducing-tests-in-legacy-php-applications"><strong>Introducing Tests in Legacy PHP Applications</strong></a><br />
                    - <a title="Speaker Jeff Carouth" href="http://2013.sunshinephp.com/schedule/speakers/#jeff-carouth">Jeff Carouth</a> -
                </td>
                <td><a title="Talk: PHPUnit Best Practices" href="http://2013.sunshinephp.com/schedule/talks/#phpunit-best-practices"><strong>PHPUnit Best Practices</strong></a><br />
                    - <a title="Speaker Sebastian Bergmann" href="http://2013.sunshinephp.com/schedule/speakers/#sebastian-bergmann">Sebastian Bergmann</a> -</td>
                <td><a title="Talk: PHP 5.5 The New Bits" href="http://2013.sunshinephp.com/schedule/talks/#php-5-5-the-new-bits"><strong>PHP 5.5: The New Bits</strong></a><br />
                    - <a title="Speaker Davey Shafik" href="http://2013.sunshinephp.com/schedule/speakers/#davey-shafik">Davey Shafik</a> -</td>
            </tr>
            <tr>
                <td>14:45 &#8211; 15:45</td>
                <td><a title="Talk: Database Testing for Fun and Profit" href="http://2013.sunshinephp.com/schedule/talks/#database-testing-for-run-and-profit"><strong>Database Testing for Fun and Profit</strong></a><br />
                    - <a title="Speaker Matthew Turland" href="http://2013.sunshinephp.com/schedule/speakers/#matthew-turland">Matthew Turland</a> -</td>
                <td><a title="Talk: From the Ground Up - Coding, Deploying, and Scaling with AWS" href="http://2013.sunshinephp.com/schedule/talks/#from-the-ground-up-coding-deploying-and-scaling-with-aws"><strong>From the Ground Up &#8211; Coding, Deploying, and Scaling with AWS</strong></a><br />
                    - <a title="Speaker Rowan Merewood" href="http://2013.sunshinephp.com/schedule/speakers/#rowan-merewood">Rowan Merewood</a> -</td>
                <td><a title="Talk: Building OpenSky with Symfony2" href="http://2013.sunshinephp.com/schedule/talks/#building-opensky-with-symfony2"><strong>Building OpenSky with Symfony2</strong></a><br />
                    - <a title="Speaker Jonathan Wage" href="http://2013.sunshinephp.com/schedule/speakers/#jonathan-wage">Jonathan Wage</a> -</td>
            </tr>
            <tr>
                <td>16:00 &#8211; 17:00</td>
                <td><a title="Talk: Silex, the Microframework" href="http://2013.sunshinephp.com/schedule/talks/#silex-the-microframework"><strong>Silex, the Microframework</strong></a><br />
                    - <a title="Speaker Ben Longden" href="http://2013.sunshinephp.com/schedule/speakers/#ben-longden">Ben Longden</a> -</td>
                <td><a title="Talk: From POX to HATEOAS, Our Companies Journey to Build a Hypermedia API" href="http://2013.sunshinephp.com/schedule/talks/#from-pox-to-hateoas-our-companies-journey-to-build-a-hypermedia-api"><strong>From POX to HATEOAS, Our Companies Journey to Build a Hypermedia API</strong></a><br />
                    - <a title="Speaker Luke Stokes" href="http://2013.sunshinephp.com/schedule/speakers/#luke-stokes">Luke Stokes</a> -</td>
                <td><a title="Talk: Overview of Windows Azure for PHP Developers" href="http://2013.sunshinephp.com/schedule/talks/#overview-of-windows-azure-for-php-developers"><strong>Overview of Windows Azure for PHP Developers</strong></a><br />
                    - <a title="Speaker Mark Brown" href="http://2013.sunshinephp.com/schedule/speakers/#mark-brown">Mark Brown</a> -</td>
            </tr>
            <tr>
                <td colspan="4"><strong>Happy Hour by php|architect</strong> from 17:30 &#8211; 19:30 featuring <strong>PHP Jeopardy Game</strong><br />
                    <strong>Mashery sponsored Hackathon</strong> 17:00 &#8211; ??? (Coffee available!)</td>
            </tr>
            </tbody>
        </table>
        <hr />
        <table>
            <tbody>
            <tr>
                <th colspan="4">Day 2 &#8211; Saturday Feb. 8th, 2014</th>
            </tr>
            <tr>
                <td>Room</td>
                <td>Key Largo 1 (front)</td>
                <td>Grand Ballrooom</td>
                <td>Key Largo 2 (rear)</td>
            </tr>
            <tr>
                <td class="time_column">9:00 &#8211; 10:00</td>
                <td class="keyrow" colspan="3">2nd Day Keynote<br />
                    !Normal==Awesome!<br />
                    <a title="Speaker Cal Evans" href="http://2013.sunshinephp.com/schedule/speakers/#cal-evans">Cal Evans</a></td>
            </tr>
            <tr>
                <td>10:15 &#8211; 11:15</td>
                <td class="talk1_column"><a title="Talk: Bringing Symfony Components into Your Legacy Code" href="http://2013.sunshinephp.com/schedule/talks/#bringing-symfony-components-into-your-legacy-code"><strong>Bringing Symfony Components into Your Legacy Code</strong></a><br />
                    - <a title="Speaker Hugo Hamon" href="http://2013.sunshinephp.com/schedule/speakers/#hugo-hamon">Hugo Hamon</a> -</td>
                <td class="talk2_column"><a title="Talk: Step By Step Making a Website Fly with Assetic, Varnish and ESI" href="http://2013.sunshinephp.com/schedule/talks/#step-by-step-making-a-website-fly-with-assetic-varnish-esi"><strong>Step By Step: Making a Website Fly with Assetic, Varnish and ESI</strong></a><br />
                    - <a title="Speaker David Buchmann" href="http://2013.sunshinephp.com/schedule/speakers/#david-buchmann">David Buchmann</a> -</td>
                <td class="talk3_column"><a title="Talk: Replication with MySQL" href="http://2013.sunshinephp.com/schedule/talks/#replication-with-mysql"><strong>Replication with MySQL</strong></a><br />
                    - <a title="Speaker Ligaya Turmelle" href="http://2013.sunshinephp.com/schedule/speakers/#ligaya-turmelle">Ligaya Turmelle</a> -</td>
            </tr>
            <tr>
                <td>11:30 &#8211; 12:30</td>
                <td><a title="Talk: Virtualized Development" href="http://2013.sunshinephp.com/schedule/talks/#virtualized-development"><strong>Virtualized Development</strong></a><br />
                    - <a title="Speaker Juozas Kaziukenas" href="http://2013.sunshinephp.com/schedule/speakers/#juozas-kaziukenas">Juozas Kaziukenas</a> -</td>
                <td><a title="Talk: Dream, Experiment, Create, and Share" href="http://2013.sunshinephp.com/schedule/talks/#dream-experiment-create-and-share"><strong>Dream, Experiment, Create, and Share</strong></a><br />
                    - <a title="Speaker Fabien Potencier" href="http://2013.sunshinephp.com/schedule/speakers/#fabien-potencier">Fabien Potencier</a> -</td>
                <td><a title="Talk: Creating Realtime Applications with PHP and Websockets" href="http://2013.sunshinephp.com/schedule/talks/#creating-realtime-applications-with-php-and-websockets"><strong>Creating Realtime Applications with PHP and Websockets</strong></a><br />
                    - <a title="Speaker Corey Ballou" href="http://2013.sunshinephp.com/schedule/speakers/#corey-ballou">Corey Ballou</a> -</td>
            </tr>
            <tr>
                <td>12:30 &#8211; 13:30</td>
                <td class="keyrow" colspan="3">Lunch</td>
            </tr>
            <tr>
                <td>13:30 &#8211; 14:30</td>
                <td><a title="Talk: DOs and DONTs of MongoDB" href="http://2013.sunshinephp.com/schedule/talks/#dos-and-donts-of-mongodb"><strong>DOs and DON’Ts of MongoDB</strong></a><br />
                    - <a title="Speaker Jeremy Mikola" href="http://2013.sunshinephp.com/schedule/speakers/#jeremy-mikola">Jeremy Mikola</a> -</td>
                <td><a title="Talk: Quickly Building and Deploying PHP Applications in the Cloud" href="http://2013.sunshinephp.com/schedule/talks/#quickly-building-and-deploying-php-applications-in-the-cloud"><strong>Quickly Building and Deploying PHP Applications in the Cloud</strong></a><br />
                    - <a title="Speaker Cory Fowler" href="http://2013.sunshinephp.com/schedule/speakers/#cory-fowler">Cory Fowler</a> -</td>
                <td><a title="Talk: Handling Forms Like a Ninja with Symfony2" href="http://2013.sunshinephp.com/schedule/talks/#handling-forms-like-a-ninja-with-symfony2"><strong>Handling Forms Like a Ninja with Symfony2</strong></a><br />
                    - <a title="Speaker Bernhard Schussek" href="http://2013.sunshinephp.com/schedule/speakers/#bernhard-schussek">Bernhard Schussek</a> -</td>
            </tr>
            <tr>
                <td>14:45 &#8211; 15:45</td>
                <td><a title="Talk: How Kris Writes Symfony Apps" href="http://2013.sunshinephp.com/schedule/talks/#how-kris-writes-symfony-apps"><strong>How Kris Writes Symfony Apps</strong></a><br />
                    - <a title="Speaker Kris Wallsmith" href="http://2013.sunshinephp.com/schedule/speakers/#kris-wallsmith">Kris Wallsmith</a> -</td>
                <td><a title="Talk: Dependency Management with Composer" href="http://2013.sunshinephp.com/schedule/talks/#dependency-management-with-composer"><strong>Dependency Management with Composer</strong></a><br />
                    - <a title="Speaker Jordi Boggiano" href="http://2013.sunshinephp.com/schedule/speakers/#jordi-boggiano">Jordi Boggiano</a> -</td>
                <td><a title="Talk: Bringing Good Design to the Table" href="http://2013.sunshinephp.com/schedule/talks/#bringing-good-design-to-the-table"><strong>Bringing Good Design to the Table</strong></a><br />
                    - <a title="Speaker Brian Fenton" href="http://2013.sunshinephp.com/schedule/speakers/#brian-fenton">Brian Fenton</a> -</td>
            </tr>
            <tr>
                <td>16:00 &#8211; 17:00</td>
                <td><a title="Talk: Cryptography for the Average Developer" href="http://2013.sunshinephp.com/schedule/talks/#cryptography-for-the-average-developer"><strong>Cryptography for the Average Developer</strong></a><br />
                    - <a title="Speaker Anthony Ferrara" href="http://2013.sunshinephp.com/schedule/speakers/#anthony-ferrara">Anthony Ferrara</a> -</td>
                <td><a title="Talk: Symfony2 + EmberJS for Fun and Profit" href="http://2013.sunshinephp.com/schedule/talks/#symfony2-plus-emberjs-for-fun-and-profit"><strong>Symfony2 + EmberJS for fun and profit</strong></a><br />
                    - <a title="Speaker Dustin Whittle" href="http://2013.sunshinephp.com/schedule/speakers/#dustin-whittle">Dustin Whittle</a> -</td>
                <td><a title="Talk: Symfony and Javascript Combining the Best of Two Worlds" href="http://2013.sunshinephp.com/schedule/talks/#symfony-and-javascript-combining-the-best-of-two-worlds"><strong>Symfony and Javascript: Combining the Best of Two Worlds</strong></a><br />
                    - <a title="Speaker Nacho Martin" href="http://2013.sunshinephp.com/schedule/speakers/#nacho-martin">Nacho Martin</a> -</td>
            </tr>
            <tr>
                <td>17:00 &#8211; 18:00</td>
                <td class="keyrow" colspan="3">Closing<br />
                    Outside the Bubble<br />
                    <a title="Speaker Keith Casey" href="http://2013.sunshinephp.com/schedule/speakers/#keith-casey">Keith Casey</a></td>
            </tr>
            <tr>
                <td colspan="4"><strong>Happy Hour by php|architect</strong> from 18:00 &#8211; 19:30 featuring <strong>PHP OOP Panel Discussion</strong><br />
                    <strong>Uncon(ference) Talks</strong> 18:00 &#8211; ???</td>
            </tr>
            </tbody>
        </table>
    </div>

</div>