<div class="page-header">
    <h1>Schedule & Layout</h1>
</div>
<div id="block-mine">
    <div id="schedule">
    
        <!-- Overall details of side rooms -->
        
        <table>
            <tbody>
            <tr>
                <th class="span12" colspan="4">Venue layout for the conference</th>
            </tr>
            <tr>
                <td class="span3"><strong>Grand Ballroom</strong></td>
                <td>Keynotes and sessions throughout each day</td>
            </tr>
            <tr>
                <td ><strong>Key Biscayne #1</strong></td>
                <td>Sessions throughout each day</td>
            </tr>
            <tr>
                <td ><strong>Key Biscayne #2</strong></td>
                <td>Sessions throughout each day</td>
            </tr>
            <tr>
                <td ><strong>Key Largo #1</strong></td>
                <td>Registration and Support</td>
            </tr>
            <tr>
                <td ><strong>Key Largo #2 and #3</strong></td>
                <td>Sponsor interaction area and coffee/snacks each day</td>
            </tr>
            <tr>
                <td ><strong>Key Largo #4</strong></td>
                <td>Wifi lounge and Uncon track each day</td>
            </tr>
            </tbody>
        </table>
        <hr />
        
        <!-- hotel layout image -->
        
        <img src="/img/hotel_layout.png" alt="Conference Layout Image" />
        <hr />

        <!-- Pre-Conference -->

        <table>
            <tbody>
            <tr>
                <th class="span12" colspan="4">Wednesday Feb. 5th, 2014</th>
            </tr>
            <tr>
                <td class="span2">17:30 &#8211; 19:30</td>
                <td class="keyrow" colspan="3"><strong>Happy Hour</strong> Atrium bar</td>
            </tr>
            </tbody>
        </table>
        <hr />
        
        <!-- Tutorial Day -->
        
        <table>
            <tbody>
            <tr>
                <th colspan="5">Tutorial Day - Feb. 6th, 2014</th>
            </tr>
            <tr>
                <td>Room</td>
                <td>Key Biscayne #1 (front)</td>
                <td>Grand Ballrooom</td>
                <td>Key Biscayne #2 (rear)</td>
                <td>Key Largo #4</td>
            </tr>
            <tr>
                <td class="span2">8:00 - 9:00</td>
                <td class="keyrow" colspan="4">Tutorial Registration Opens - Key Largo #1</td>
            </tr>
            <tr>
                <td>9:00 - 12:00</td>
                <td class="span3"><a title="Talk: Symfony2 Introduction" href="http://2013.sunshinephp.com/schedule/talks/#symfony2-introduction"><strong>Symfony2 Intro</strong></a><br />
                    - <a title="Speaker David Buchmann" href="http://2013.sunshinephp.com/schedule/speakers/#david-buchmann">David Buchmann</a> -</td>
                <td class="span3"><a title="Talk: Continuous Integration in Real Life" href="http://2013.sunshinephp.com/schedule/talks/#continuous-integration-in-real-life"><strong>Continuous Integration in Real Life</strong></a><br />
                    - <a title="Speaker Beth Tucker Long" href="http://2013.sunshinephp.com/schedule/speakers/#beth-tucker-long">Beth Tucker Long</a> -</td>
                <td class="span3"><a title="Talk: Functional PHP" href="http://2013.sunshinephp.com/schedule/talks/#functional-php"><strong>Functional PHP</strong></a><br />
                    - <a title="Speaker Larry Garfield" href="http://2013.sunshinephp.com/schedule/speakers/#larry-garfield">Larry Garfield</a> -</td>
                <td class="span3"><a title="Talk: Functional PHP" href="http://2013.sunshinephp.com/schedule/talks/#functional-php"><strong>Functional PHP</strong></a><br />
                    - <a title="Speaker Larry Garfield" href="http://2013.sunshinephp.com/schedule/speakers/#larry-garfield">Larry Garfield</a> -</td>
            </tr>
            <tr>
                <td>12:00 - 13:00</td>
                <td class="keyrow" colspan="4">Lunch</td>
            </tr>
            <tr>
                <td>13:00 - 16:00</td>
                <td><a title="Talk: Symfony2 Introduction" href="http://2013.sunshinephp.com/schedule/talks/#symfony2-introduction"><strong>Symfony2 Intro</strong></a><br />
                    - <a title="Speaker David Buchmann" href="http://2013.sunshinephp.com/schedule/speakers/#david-buchmann">David Buchmann</a> -</td>
                <td><a title="Talk: Continuous Integration in Real Life" href="http://2013.sunshinephp.com/schedule/talks/#continuous-integration-in-real-life"><strong>Continuous Integration in Real Life</strong></a><br />
                    - <a title="Speaker Beth Tucker Long" href="http://2013.sunshinephp.com/schedule/speakers/#beth-tucker-long">Beth Tucker Long</a> -</td>
                <td><a title="Talk: Functional PHP" href="http://2013.sunshinephp.com/schedule/talks/#functional-php"><strong>Functional PHP</strong></a><br />
                    - <a title="Speaker Larry Garfield" href="http://2013.sunshinephp.com/schedule/speakers/#larry-garfield">Larry Garfield</a> -</td>
                <td><a title="Talk: Functional PHP" href="http://2013.sunshinephp.com/schedule/talks/#functional-php"><strong>Functional PHP</strong></a><br />
                    - <a title="Speaker Larry Garfield" href="http://2013.sunshinephp.com/schedule/speakers/#larry-garfield">Larry Garfield</a> -</td>
            </tr>
            <tr>
                <td>17:30 - 19:30</td>
                <td class="keyrow" colspan="4"><strong>Happy Hour</strong> Atrium bar</td>
            </tr>
            </tbody>
        </table>
        <hr />
        
        <!-- Day #1 -->
        
        <table>
            <tbody>
            <tr>
                <th colspan="5">Day 1 - Friday Feb. 7th, 2014</th>
            </tr>
            <tr>
                <td>Room</td>
                <td>Key Biscayne #1 (front)</td>
                <td>Grand Ballrooom</td>
                <td>Key Biscayne #2 (rear)</td>
                <td>Key Largo #4</td>
            </tr>
            <tr>
                <td class="span2">8:00 - 9:00</td>
                <td colspan="4"><strong>Conference Registration Opens</strong> Key Largo #1</td>
            </tr>
            <tr>
                <td>9:00 - 10:00</td>
                <td class="keyrow" colspan="4">Opening Keynote<br />
                    PHP in 2013<br />
                    <a title="Speaker Rasmus Lerdorf" href="http://2013.sunshinephp.com/schedule/speakers/#rasmus-lerdorf">Rasmus Lerdorf</a></td>
            </tr>
            <tr>
                <td>10:15 - 11:15</td>
                <td class="span3"><a title="Talk: Symfony2 Introduction" href="http://2013.sunshinephp.com/schedule/talks/#symfony2-introduction"><strong>Symfony2 Intro</strong></a><br />
                    - <a title="Speaker David Buchmann" href="http://2013.sunshinephp.com/schedule/speakers/#david-buchmann">David Buchmann</a> -</td>
                <td class="span3"><a title="Talk: Continuous Integration in Real Life" href="http://2013.sunshinephp.com/schedule/talks/#continuous-integration-in-real-life"><strong>Continuous Integration in Real Life</strong></a><br />
                    - <a title="Speaker Beth Tucker Long" href="http://2013.sunshinephp.com/schedule/speakers/#beth-tucker-long">Beth Tucker Long</a> -</td>
                <td class="span3"><a title="Talk: Functional PHP" href="http://2013.sunshinephp.com/schedule/talks/#functional-php"><strong>Functional PHP</strong></a><br />
                    - <a title="Speaker Larry Garfield" href="http://2013.sunshinephp.com/schedule/speakers/#larry-garfield">Larry Garfield</a> -</td>
                <td class="span2">See Uncon Poster</td>
            </tr>
            <tr>
                <td>11:30 - 12:30</td>
                <td><a title="Talk: Introduction to Modules in Zend Framework 2" href="http://2013.sunshinephp.com/schedule/talks/#introduction-to-modules-in-zend-framework2"><strong>Introduction to Modules in Zend Framework 2</strong></a><br />
                    - <a title="Speaker Evan Coury" href="http://2013.sunshinephp.com/schedule/speakers/#evan-coury">Evan Coury</a> -</td>
                <td><a title="Talk: It Was Like That When I Got Here Steps Toward Modernizing a Legacy Codebase" href="http://2013.sunshinephp.com/schedule/talks/#it-was-like-that-when-i-got-here-steps-toward-modernizing-a-legacy-codebase"><strong>It Was Like That When I Got Here: Steps Toward Modernizing a Legacy Codebase</strong></a><br />
                    - <a title="Speaker Paul M. Jones" href="http://2013.sunshinephp.com/schedule/speakers/#paul-m-jones">Paul M. Jones</a> -</td>
                <td><a title="Talk: Twig Tips and Tricks" href="http://2013.sunshinephp.com/schedule/talks/#twig-tips-and-tricks"><strong>Twig Tips and Tricks</strong></a><br />
                    - <a title="Speaker Javier Equiluz" href="http://2013.sunshinephp.com/schedule/speakers/#javier-equiluz">Javier Equiluz</a> -</td>
                <td>See Uncon Poster</td>
            </tr>
            <tr>
                <td>12:30 - 13:30</td>
                <td colspan="4">Lunch</td>
            </tr>
            <tr>
                <td>13:30 - 14:30</td>
                <td class="keyrow" colspan="4">Keynote<br />
                    <a title="Speaker Rasmus Lerdorf" href="http://2013.sunshinephp.com/schedule/speakers/#rasmus-lerdorf">Rasmus Lerdorf</a></td>
            </tr>
            <tr>
                <td>14:45 - 15:45</td>
                <td><a title="Talk: Database Testing for Fun and Profit" href="http://2013.sunshinephp.com/schedule/talks/#database-testing-for-run-and-profit"><strong>Database Testing for Fun and Profit</strong></a><br />
                    - <a title="Speaker Matthew Turland" href="http://2013.sunshinephp.com/schedule/speakers/#matthew-turland">Matthew Turland</a> -</td>
                <td><a title="Talk: From the Ground Up - Coding, Deploying, and Scaling with AWS" href="http://2013.sunshinephp.com/schedule/talks/#from-the-ground-up-coding-deploying-and-scaling-with-aws"><strong>From the Ground Up &#8211; Coding, Deploying, and Scaling with AWS</strong></a><br />
                    - <a title="Speaker Rowan Merewood" href="http://2013.sunshinephp.com/schedule/speakers/#rowan-merewood">Rowan Merewood</a> -</td>
                <td><a title="Talk: Building OpenSky with Symfony2" href="http://2013.sunshinephp.com/schedule/talks/#building-opensky-with-symfony2"><strong>Building OpenSky with Symfony2</strong></a><br />
                    - <a title="Speaker Jonathan Wage" href="http://2013.sunshinephp.com/schedule/speakers/#jonathan-wage">Jonathan Wage</a> -</td>
                <td>See Uncon Poster</td>
            </tr>
            <tr>
                <td>16:00 - 17:00</td>
                <td><a title="Talk: Silex, the Microframework" href="http://2013.sunshinephp.com/schedule/talks/#silex-the-microframework"><strong>Silex, the Microframework</strong></a><br />
                    - <a title="Speaker Ben Longden" href="http://2013.sunshinephp.com/schedule/speakers/#ben-longden">Ben Longden</a> -</td>
                <td><a title="Talk: From POX to HATEOAS, Our Companies Journey to Build a Hypermedia API" href="http://2013.sunshinephp.com/schedule/talks/#from-pox-to-hateoas-our-companies-journey-to-build-a-hypermedia-api"><strong>From POX to HATEOAS, Our Companies Journey to Build a Hypermedia API</strong></a><br />
                    - <a title="Speaker Luke Stokes" href="http://2013.sunshinephp.com/schedule/speakers/#luke-stokes">Luke Stokes</a> -</td>
                <td><a title="Talk: Overview of Windows Azure for PHP Developers" href="http://2013.sunshinephp.com/schedule/talks/#overview-of-windows-azure-for-php-developers"><strong>Overview of Windows Azure for PHP Developers</strong></a><br />
                    - <a title="Speaker Mark Brown" href="http://2013.sunshinephp.com/schedule/speakers/#mark-brown">Mark Brown</a> -</td>
                <td>See Uncon Poster</td>
            </tr>
            <tr>
                <td>17:15 - 18:15</td>
                <td><a title="Talk: Silex, the Microframework" href="http://2013.sunshinephp.com/schedule/talks/#silex-the-microframework"><strong>Silex, the Microframework</strong></a><br />
                    - <a title="Speaker Ben Longden" href="http://2013.sunshinephp.com/schedule/speakers/#ben-longden">Ben Longden</a> -</td>
                <td><a title="Talk: From POX to HATEOAS, Our Companies Journey to Build a Hypermedia API" href="http://2013.sunshinephp.com/schedule/talks/#from-pox-to-hateoas-our-companies-journey-to-build-a-hypermedia-api"><strong>From POX to HATEOAS, Our Companies Journey to Build a Hypermedia API</strong></a><br />
                    - <a title="Speaker Luke Stokes" href="http://2013.sunshinephp.com/schedule/speakers/#luke-stokes">Luke Stokes</a> -</td>
                <td><a title="Talk: Overview of Windows Azure for PHP Developers" href="http://2013.sunshinephp.com/schedule/talks/#overview-of-windows-azure-for-php-developers"><strong>Overview of Windows Azure for PHP Developers</strong></a><br />
                    - <a title="Speaker Mark Brown" href="http://2013.sunshinephp.com/schedule/speakers/#mark-brown">Mark Brown</a> -</td>
                <td>See Uncon Poster</td>
            </tr>
            <tr>
                <td class="keyrow" colspan="5"><strong>Happy Hour</strong> from 18:30 - 19:30 featuring <strong>What's it Game</strong> Grand Ballroom<br />
                    <strong>Windows Azure sponsored Hackathon</strong> 19:00 - ??? (Food available!)</td>
            </tr>
            </tbody>
        </table>
        <hr />
        
        <!-- Day #2 -->

        <table>
            <tbody>
            <tr>
                <th colspan="5">Day 1 - Friday Feb. 7th, 2014</th>
            </tr>
            <tr>
                <td>Room</td>
                <td>Key Biscayne #1 (front)</td>
                <td>Grand Ballrooom</td>
                <td>Key Biscayne #2 (rear)</td>
                <td>Key Largo #4</td>
            </tr>
            <tr>
                <td class="span2">8:00 - 9:00</td>
                <td colspan="4">Registration Opens</td>
            </tr>
            <tr>
                <td>9:00 - 10:00</td>
                <td class="keyrow" colspan="4">Opening Keynote<br />
                    PHP in 2013<br />
                    <a title="Speaker Rasmus Lerdorf" href="http://2013.sunshinephp.com/schedule/speakers/#rasmus-lerdorf">Rasmus Lerdorf</a></td>
            </tr>
            <tr>
                <td>10:15 - 11:15</td>
                <td class="span4"><a title="Talk: Symfony2 Introduction" href="http://2013.sunshinephp.com/schedule/talks/#symfony2-introduction"><strong>Symfony2 Intro</strong></a><br />
                    - <a title="Speaker David Buchmann" href="http://2013.sunshinephp.com/schedule/speakers/#david-buchmann">David Buchmann</a> -</td>
                <td class="span4"><a title="Talk: Continuous Integration in Real Life" href="http://2013.sunshinephp.com/schedule/talks/#continuous-integration-in-real-life"><strong>Continuous Integration in Real Life</strong></a><br />
                    - <a title="Speaker Beth Tucker Long" href="http://2013.sunshinephp.com/schedule/speakers/#beth-tucker-long">Beth Tucker Long</a> -</td>
                <td class="span4"><a title="Talk: Functional PHP" href="http://2013.sunshinephp.com/schedule/talks/#functional-php"><strong>Functional PHP</strong></a><br />
                    - <a title="Speaker Larry Garfield" href="http://2013.sunshinephp.com/schedule/speakers/#larry-garfield">Larry Garfield</a> -</td>
                <td class="span2">See Uncon Poster</td>
            </tr>
            <tr>
                <td>11:30 - 12:30</td>
                <td><a title="Talk: Introduction to Modules in Zend Framework 2" href="http://2013.sunshinephp.com/schedule/talks/#introduction-to-modules-in-zend-framework2"><strong>Introduction to Modules in Zend Framework 2</strong></a><br />
                    - <a title="Speaker Evan Coury" href="http://2013.sunshinephp.com/schedule/speakers/#evan-coury">Evan Coury</a> -</td>
                <td><a title="Talk: It Was Like That When I Got Here Steps Toward Modernizing a Legacy Codebase" href="http://2013.sunshinephp.com/schedule/talks/#it-was-like-that-when-i-got-here-steps-toward-modernizing-a-legacy-codebase"><strong>It Was Like That When I Got Here: Steps Toward Modernizing a Legacy Codebase</strong></a><br />
                    - <a title="Speaker Paul M. Jones" href="http://2013.sunshinephp.com/schedule/speakers/#paul-m-jones">Paul M. Jones</a> -</td>
                <td><a title="Talk: Twig Tips and Tricks" href="http://2013.sunshinephp.com/schedule/talks/#twig-tips-and-tricks"><strong>Twig Tips and Tricks</strong></a><br />
                    - <a title="Speaker Javier Equiluz" href="http://2013.sunshinephp.com/schedule/speakers/#javier-equiluz">Javier Equiluz</a> -</td>
                <td>See Uncon Poster</td>
            </tr>
            <tr>
                <td>12:30 - 13:30</td>
                <td colspan="4">Lunch</td>
            </tr>
            <tr>
                <td>13:30 - 14:30</td>
                <td class="keyrow" colspan="4">Keynote<br />
                    <a title="Speaker Rasmus Lerdorf" href="http://2013.sunshinephp.com/schedule/speakers/#rasmus-lerdorf">Rasmus Lerdorf</a></td>
            </tr>
            <tr>
                <td>14:45 - 15:45</td>
                <td><a title="Talk: Database Testing for Fun and Profit" href="http://2013.sunshinephp.com/schedule/talks/#database-testing-for-run-and-profit"><strong>Database Testing for Fun and Profit</strong></a><br />
                    - <a title="Speaker Matthew Turland" href="http://2013.sunshinephp.com/schedule/speakers/#matthew-turland">Matthew Turland</a> -</td>
                <td><a title="Talk: From the Ground Up - Coding, Deploying, and Scaling with AWS" href="http://2013.sunshinephp.com/schedule/talks/#from-the-ground-up-coding-deploying-and-scaling-with-aws"><strong>From the Ground Up &#8211; Coding, Deploying, and Scaling with AWS</strong></a><br />
                    - <a title="Speaker Rowan Merewood" href="http://2013.sunshinephp.com/schedule/speakers/#rowan-merewood">Rowan Merewood</a> -</td>
                <td><a title="Talk: Building OpenSky with Symfony2" href="http://2013.sunshinephp.com/schedule/talks/#building-opensky-with-symfony2"><strong>Building OpenSky with Symfony2</strong></a><br />
                    - <a title="Speaker Jonathan Wage" href="http://2013.sunshinephp.com/schedule/speakers/#jonathan-wage">Jonathan Wage</a> -</td>
                <td>See Uncon Poster</td>
            </tr>
            <tr>
                <td>16:00 - 17:00</td>
                <td><a title="Talk: Silex, the Microframework" href="http://2013.sunshinephp.com/schedule/talks/#silex-the-microframework"><strong>Silex, the Microframework</strong></a><br />
                    - <a title="Speaker Ben Longden" href="http://2013.sunshinephp.com/schedule/speakers/#ben-longden">Ben Longden</a> -</td>
                <td><a title="Talk: From POX to HATEOAS, Our Companies Journey to Build a Hypermedia API" href="http://2013.sunshinephp.com/schedule/talks/#from-pox-to-hateoas-our-companies-journey-to-build-a-hypermedia-api"><strong>From POX to HATEOAS, Our Companies Journey to Build a Hypermedia API</strong></a><br />
                    - <a title="Speaker Luke Stokes" href="http://2013.sunshinephp.com/schedule/speakers/#luke-stokes">Luke Stokes</a> -</td>
                <td><a title="Talk: Overview of Windows Azure for PHP Developers" href="http://2013.sunshinephp.com/schedule/talks/#overview-of-windows-azure-for-php-developers"><strong>Overview of Windows Azure for PHP Developers</strong></a><br />
                    - <a title="Speaker Mark Brown" href="http://2013.sunshinephp.com/schedule/speakers/#mark-brown">Mark Brown</a> -</td>
                <td>See Uncon Poster</td>
            </tr>
            <tr>
                <td>17:15 - 18:15</td>
                <td><a title="Talk: Silex, the Microframework" href="http://2013.sunshinephp.com/schedule/talks/#silex-the-microframework"><strong>Silex, the Microframework</strong></a><br />
                    - <a title="Speaker Ben Longden" href="http://2013.sunshinephp.com/schedule/speakers/#ben-longden">Ben Longden</a> -</td>
                <td><a title="Talk: From POX to HATEOAS, Our Companies Journey to Build a Hypermedia API" href="http://2013.sunshinephp.com/schedule/talks/#from-pox-to-hateoas-our-companies-journey-to-build-a-hypermedia-api"><strong>From POX to HATEOAS, Our Companies Journey to Build a Hypermedia API</strong></a><br />
                    - <a title="Speaker Luke Stokes" href="http://2013.sunshinephp.com/schedule/speakers/#luke-stokes">Luke Stokes</a> -</td>
                <td><a title="Talk: Overview of Windows Azure for PHP Developers" href="http://2013.sunshinephp.com/schedule/talks/#overview-of-windows-azure-for-php-developers"><strong>Overview of Windows Azure for PHP Developers</strong></a><br />
                    - <a title="Speaker Mark Brown" href="http://2013.sunshinephp.com/schedule/speakers/#mark-brown">Mark Brown</a> -</td>
                <td>See Uncon Poster</td>
            </tr>
            <tr>
                <td>18:30 - 19:00</td>
                <td class="keyrow" colspan="4"><strong>Closing Keynote & Drawings</strong><br />
                    <a title="Speaker Rasmus Lerdorf" href="http://2013.sunshinephp.com/schedule/speakers/#rasmus-lerdorf">Rasmus Lerdorf</a></td>
            </tr>
            </tbody>
        </table>
        <hr />
    </div>

</div>