<div class="page-header" xmlns="http://www.w3.org/1999/html">
    <h1>Uncon</h1>
</div>
<div id="block-mine">
    <p style="text-align: justify;">
    
         What is an "Uncon"?  Simply put, it's a group of talks not considered part of the normal conference schedule.  These talks are possibly talks that we were not able to fit into the schedule, or perhaps they are talks that are new and the speaker is taking advantage of this opening to test the waters and tweak it.  This is also a great way for those who would like to speak to hone their skills.<br /><br />
    
        This year instead of having a small window of time, to cram as many talks in as we can, we decided to create an entire 4th track dedicated to it.<br /><br />
    
        Want to give a talk at the Uncon?  There will be a board posted in a central location for all to see.  See the orgnizer, or tweet to us at <a href="https://twitter.com/SunshinePHP" title="@SunshinePHP">@SunshinePHP</a>, <strong>during the conference</strong> to get your spot.<br /><br />
        
    </p>
</div>