<div class="page-header" xmlns="http://www.w3.org/1999/html">
    <h1>Uncon</h1>
</div>
<div id="block-mine">
    <p style="text-align: justify;">
    
        <div style="float:right; padding-left: 10px;"><img src="/img/dragonbe.jpg" alt="Michelangelo Van Dam" /></div> What is an "Uncon"?  Simply put, it's a group of talks not considered part of the normal conference schedule.  These talks are possibly talks that we were not able to fit into the schedule, or perhaps they are talks that are new and the speaker is taking advantage of this opening to test the waters and tweak it.  This is also a great way for those who would like to speak to hone their skills.<br /><br />
    
        This year instead of having a small window of time, to cram as many talks in as we can, we decided to create an entire 4th track dedicated to it, and the fine folks at <a href="http://constantcontact.com" title="Constant Contact">Constant Contact</a> have graciously sponsored this portion of the event.<br /><br />
    
        Want to give a talk at the Uncon?  There will be a board posted in a central location for all to see.  See Michelangelo Van Dam, or tweet to him <a href="https://twitter.com/DragonBe" title="@DragonBe">@DragonBe</a>, <strong>during the conference</strong> to get your spot.<br /><br />
        
    </p>
    <p style="text-align: center">
        <img src="/img/sponsor_badges/constantcontact.png" alt="Constant Contact" />
    </p>
</div>