<div class="page-header" xmlns="http://www.w3.org/1999/html">
    <h1>Uncon</h1>
</div>
<div id="block-mine">
    <p style="text-align: justify;">
        What is an "Uncon"?  Simply put, it's a group of talks not considered part 
        of the normal conference schedule.  These are possibly talks we were not 
        able to fit into the regular schedule, or perhaps they are talks that are 
        new and the speaker is taking advantage of this opening to test the waters 
        and tweak it.  This is also a great way for new speakers to hone their skills.<br /><br />
    
        Instead of a small time window, to cram as many talks as we can, SunshinePHP 
        decided to create an <strong>entire 4th track</strong> dedicated to it.<br /><br />
    
        Want to give a talk at the Uncon?  There will be a board posted in a central 
        location for all to see.  See the orgnizer, or tweet to us at 
        <a href="https://twitter.com/SunshinePHP" title="@SunshinePHP">@SunshinePHP</a>, <strong>during the conference</strong> to get your spot.<br /><br />
        
        <strong>How to register:</strong> The empty board is posted at 8:00am each morning by the Uncon room. 
        But we warned, it fills up within the first 15 minutes.  So time is critical 
        if you want to get your talk on it.
    </p>
</div>