<div class="page-header">
    <h1>Location & Hotel</h1>
</div>
<div id="block-mine">
    <p style="text-align: justify;">
        The SunshinePHP Developer Conference venue will be Embassy Suites Miami International.  The hotel will be a wonderful setting for the event with a beautiful tropical themed atrium, newly renovated restaurant, Starbucks coffee station, great patio with a pool (shown below), and session rooms close by one another with sponsor tables nestled in the middle.
    </p>
    <p style="text-align: center;">
        <a href="/img/ES_exterior_712x342_FitToBoxSmallDimension_Center.jpg"><img class="aligncenter" title="Exterior" src="/img/ES_exterior_712x342_FitToBoxSmallDimension_Center.jpg" alt="Embassy Suites Miami International" /></a>
    </p>
    <p style="text-align: justify;">
        If you have not registered for this PHP conference yet, now is the time register and take advantage of the special rate.  Register early to take advantage of the special hotel room rate for all attendees the event. (<strong>Full "made to order" breakfast is included.</strong>) The conference will have events planned for both nights of February 2nd and 4th, so we recommend that you stay for 4 nights (or 3 nights if you are not attending the tutorial day), arriving on February 1st, and leaving on the 5th.  This will ensure you arrive the day before the conference to be well rested for a day crammed with great talks.  Then leave the day after, so you can take advantage of the evening events on the last day.
    </p>
    <p>
        <strong>Use this link by January 9th <em>(first-come, first-served)</em> or call them directly</strong> to get the special rate: <a href="http://embassysuites.hilton.com/en/es/groups/personalized/M/MIASPES-PHP-20170202/index.jhtml?WT.mc_id=POG" title="Embassy Suites Miami International" target="_blank">Embassy Suites Miami International</a><br />
        Hotel Phone: (305) 634-5000 or 1-800-EMBASSY (GROUP CODE: PHP)
    </p>
    <p style="text-align: center">
        <strong>Embassy Suites Miami International</strong><br />
        3974 NW South River Drive<br />
        Miami, Florida 33142<br />
    </p>
    <p style="text-align: justify;">
        Yes, the hotel provides a shuttle to and from the airport as well as a secure parking lot for those driving to the SunshinePHP conference.  If you are staying at the hotel the <strong>parking is free</strong>, and for those who are not staying at the hotel we have negotiated a low parking rate.
    </p>
    <p style="text-align: justify;">
        For those who like physical fitness while you travel, they also have a really nice gym with plenty of treadmills and other machines.
    </p>
    <p style="text-align: justify;">
        There is also a small store on-site for those little forgotten items, or if you need something urgently.
    </p>
    <p style="text-align: justify;">
        And did we forget to mention?  They also have FREE wifi for everyone staying at the hotel, and we will get a code for the rest of the attendees to use so they have the free wifi also. ;)
    </p>

<!--    <p>Below is the floor plan of the hotel.  See <a href="/schedule" title="Schedule & Layout">Schedule & Layout</a> for more details on where everything is happening. </p>-->
    <img src="/img/hotel_layout.png" alt="Conference Layout Image" />

</div>