<div class="page-header">
    <h1>Venue</h1>
</div>
<div id="block-mine">
    <p style="text-align: justify;">
        The 2014 SunshinePHP Developer Conference venue will be Embassy Suites Miami International.  The hotel will be a wonderful setting for the event with a beautiful tropical themed atrium, newly renovated restaurant, Starbucks coffee station, great patio with a pool (shown below), and session rooms close by one another with sponsor tables nestled in the middle.
    </p>
    <p style="text-align: center;">
        <a href="http://2013.sunshinephp.com/wp-content/uploads/2012/11/ES_exterior_712x342_FitToBoxSmallDimension_Center.jpg"><img class="aligncenter" title="Exterior" src="http://2013.sunshinephp.com/wp-content/uploads/2012/11/ES_exterior_712x342_FitToBoxSmallDimension_Center-300x144.jpg" alt="Embassy Suites Miami International" width="300" height="144" /></a>
    </p>
    <p style="text-align: justify;">
        If you have not registered for this PHP conference yet, now is the time register and take advantage of the early bird special rate.  You can also take advantage of the special hotel room rate of $175 set for all attendees the event. (<strong>Full "made to order" breakfast is included.</strong>) The conference will have events planned for both nights of February 6th and 8th, so we recommend that you stay for 4 nights (or 3 nights if you are not attending the tutorial day), arriving on February 5th, and leaving on the 9th.  This will ensure you arrive the day before the conference to be well rested for a day crammed with great talks.  Then leave the day after, so you can take advantage of the evening events on the last day.
    </p>
    <p>
        <strong>Use this link by Dec. 15th or call them directly to get the special rate: <a href="http://embassysuites.hilton.com/en/es/groups/personalized/M/MIASPES-PHP-20140205/index.jhtml" title="Embassy Suites Miami International" target="_blank">Embassy Suites Miami International</a></strong><br />
        Hotel Phone: (305) 634-5000
    </p>
    <p style="text-align: justify;">
        Yes, the hotel provides a shuttle to and from the airport as well as a secure parking lot for those driving to the SunshinePHP conference.  If you are staying at the hotel the <strong>parking will be free</strong>, and for those who are not staying at the hotel we have negotiated a low $5/day parking rate.
    </p>
    <p style="text-align: justify;">
        For those who like physical fitness while you travel, they also have a really nice gym with plenty of treadmills and other machines.
    </p>
    <p style="text-align: justify;">
        There is also a small store on-site for those little forgotten items, or if you need something urgently.
    </p>
    <p style="text-align: justify;">
        And did we forget to mention?  They also have FREE wifi for everyone staying at the hotel, and we will get a code for the rest of the attendees to use so they have the free wifi also. ;)
    </p>

</div>