<div class="span3">
    <div class="widget" id="mc_embed_signup">
        <h3>Newsletter</h3>
        <form action="http://sunshinephp.us6.list-manage.com/subscribe/post?u=f6982e96ad914a99e45e6b5a9&amp;id=5e6481c356" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate form-signup-home fade-in three" target="_blank" novalidate>
            <label for="mce-EMAIL">Signup for Notifications</label>
            <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required />
            <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
            <div style="position: absolute; left: -5000px;"><input type="text" name="b_f6982e96ad914a99e45e6b5a9_5e6481c356" tabindex="-1" value=""></div>
            <span class="clear text-center clearfix">
                <input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button" />
            </span>
        </form>
    </div>
    
    <div class="widget" id="t_embed">
        <h3>Sponsors</h3>
        <a href="/sponsors" title="Be a Sponsor!">Please be a sponsor.</a>
    
        <br /><br />
        <a href="http://knpuniversity.com" title="KNP University" target="_blank">
            <img src="/img/sponsor_badges/knp.png" alt="KNP University" />
        </a>
        
    </div>
    
</div>