<div class="span3">
    <div class="widget" id="mc_embed_signup">
        <h3>Newsletter</h3>
        <form action="http://uniquewebsites.us6.list-manage.com/subscribe/post?u=f6982e96ad914a99e45e6b5a9&amp;id=48ad0ac116" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate form-signup-home fade-in three" target="_blank" novalidate>
            <label for="mce-EMAIL">Signup for SunshinePHP notifications</label>
            <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required />
                                        <span class="clear text-center clearfix">
                                            <input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button" />
                                        </span>
        </form>
    </div>
    
    <div class="widget" id="t_embed">
        <h3>Sponsors</h3>
        <a href="/sponsors" title="Be a Sponsor!">Please be a sponsor.</a>
        
    </div>
    
</div>