<div class="span3">
    <div class="widget" id="mc_embed_signup">
        <h3>Newsletter</h3>
        <form action="http://uniquewebsites.us6.list-manage.com/subscribe/post?u=f6982e96ad914a99e45e6b5a9&amp;id=48ad0ac116" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate form-signup-home fade-in three" target="_blank" novalidate>
            <label for="mce-EMAIL">Signup for SunshinePHP notifications</label>
            <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required />
                                        <span class="clear text-center clearfix">
                                            <input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button" />
                                        </span>
        </form>
    </div>
    
    <div class="widget" id="t_embed">
        <h3>Sponsors</h3>
        <a href="http://windowsazure.com" title="Windows Azure" target="_blank">
            <img src="/img/sponsor_badges/windows_azure.png" alt="Windows Azure" />
        </a>

        <br /><br />
        <a href="http://zend.com" title="Zend Technologies" target="_blank">
            <img src="/img/sponsor_badges/zend.png" alt="Zend Technologies" />
        </a>

        <br /><br />
        <a href="http://engineyard.com" title="Engine Yard" target="_blank">
            <img src="/img/sponsor_badges/engineyard.png" alt="Engine Yard" />
        </a>

        <br /><br />
        <a href="http://www.appdynamics.com/" title="AppDynamics" target="_blank">
            <img src="/img/sponsor_badges/appdynamics.png" alt="AppDynamics" />
        </a>

        <br /><br />
        <a href="http://in2it.be" title="in2it" target="_blank">
            <img src="/img/sponsor_badges/in2it.png" alt="in2it" />
        </a>

        <br /><br />
        <a href="http://knpuniversity.com" title="KNP University" target="_blank">
            <img src="/img/sponsor_badges/knp.png" alt="KNP University" />
        </a>

        <br /><br />
        <a href="http://foxycart.com" title="FoxyCart!" target="_blank">
            <img src="/img/sponsor_badges/foxycart.png" alt="FoxyCart!" />
        </a>

        <br /><br />
        <a href="http://mysql.com" title="MySQL" target="_blank">
            <img src="/img/sponsor_badges/mysql.png" alt="MySQL" />
        </a>

        <br /><br />
        <a href="http://github.com" title="GitHub" target="_blank">
            <img src="/img/sponsor_badges/github.png" alt="GitHub" />
        </a>

        <br /><br />
        <a href="http://roave.com" title="Roave" target="_blank">
            <img src="/img/sponsor_badges/roave.png" alt="Roave" />
        </a>

        <br /><br />
        <a href="http://www.jetbrains.com/phpstorm/" title="PHPStorm" target="_blank">
            <img src="/img/sponsor_badges/phpstorm.png" alt="PHPStorm" />
        </a>

        <br /><br />
        <a href="http://servergrove.com" title="ServerGrove" target="_blank">
            <img src="/img/sponsor_badges/sg_lanyards.png" alt="ServerGrove" />
        </a>

        <br /><br />
        <a href="http://constantcontact.com" title="Constant Contact" target="_blank">
            <img src="/img/sponsor_badges/constantcontact.png" alt="Constant Contact" />
        </a>
    </div>
    
</div>